import { db } from '@/db';
import { hospitalSnapshots } from '@/db/schema';

async function main() {
    const now = new Date();
    const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    
    const getRandomTimestamp = (index: number) => {
        const timeRange = now.getTime() - sevenDaysAgo.getTime();
        const randomTime = sevenDaysAgo.getTime() + (timeRange * index / 12);
        return new Date(randomTime).toISOString();
    };

    const hospitalCapacities = {
        'MED-CENTRAL-001': 600,
        'MED-CENTRAL-002': 500,
        'MED-CENTRAL-003': 400,
        'MED-CENTRAL-004': 300,
        'MED-CENTRAL-005': 200,
    };

    const sampleSnapshots = [
        // MED-CENTRAL-001 (600 beds - Large Hospital)
        // Normal Load (4 snapshots)
        {
            hospitalId: 'MED-CENTRAL-001',
            timestamp: getRandomTimestamp(0),
            bedsTotal: 600,
            bedsFree: 150,
            doctorsOnShift: 22,
            nursesOnShift: 52,
            oxygenCylinders: 165,
            ventilators: 42,
            medicines: { paracetamol: 650, aspirin: 420, antibiotics: 325, insulin: 245, morphine: 118 },
            incomingEmergencies: 3,
            incidentDescription: 'Routine operations',
            aqi: 78,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(0),
        },
        {
            hospitalId: 'MED-CENTRAL-001',
            timestamp: getRandomTimestamp(1),
            bedsTotal: 600,
            bedsFree: 135,
            doctorsOnShift: 19,
            nursesOnShift: 48,
            oxygenCylinders: 142,
            ventilators: 38,
            medicines: { paracetamol: 580, aspirin: 385, antibiotics: 298, insulin: 220, morphine: 95 },
            incomingEmergencies: 4,
            incidentDescription: null,
            aqi: 92,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(1),
        },
        {
            hospitalId: 'MED-CENTRAL-001',
            timestamp: getRandomTimestamp(2),
            bedsTotal: 600,
            bedsFree: 168,
            doctorsOnShift: 24,
            nursesOnShift: 55,
            oxygenCylinders: 188,
            ventilators: 46,
            medicines: { paracetamol: 720, aspirin: 465, antibiotics: 358, insulin: 272, morphine: 132 },
            incomingEmergencies: 2,
            incidentDescription: 'Routine operations',
            aqi: 65,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(2),
        },
        {
            hospitalId: 'MED-CENTRAL-001',
            timestamp: getRandomTimestamp(3),
            bedsTotal: 600,
            bedsFree: 144,
            doctorsOnShift: 20,
            nursesOnShift: 50,
            oxygenCylinders: 155,
            ventilators: 40,
            medicines: { paracetamol: 610, aspirin: 398, antibiotics: 312, insulin: 235, morphine: 108 },
            incomingEmergencies: 5,
            incidentDescription: null,
            aqi: 85,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(3),
        },
        // Medium Load (5 snapshots)
        {
            hospitalId: 'MED-CENTRAL-001',
            timestamp: getRandomTimestamp(4),
            bedsTotal: 600,
            bedsFree: 84,
            doctorsOnShift: 16,
            nursesOnShift: 42,
            oxygenCylinders: 78,
            ventilators: 32,
            medicines: { paracetamol: 485, aspirin: 315, antibiotics: 245, insulin: 188, morphine: 82 },
            incomingEmergencies: 9,
            incidentDescription: 'Minor traffic accident nearby',
            aqi: 145,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(4),
        },
        {
            hospitalId: 'MED-CENTRAL-001',
            timestamp: getRandomTimestamp(5),
            bedsTotal: 600,
            bedsFree: 96,
            doctorsOnShift: 18,
            nursesOnShift: 46,
            oxygenCylinders: 92,
            ventilators: 36,
            medicines: { paracetamol: 530, aspirin: 348, antibiotics: 272, insulin: 205, morphine: 95 },
            incomingEmergencies: 7,
            incidentDescription: 'Food poisoning outbreak at local event',
            aqi: 128,
            festival: 'Holi',
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(5),
        },
        {
            hospitalId: 'MED-CENTRAL-001',
            timestamp: getRandomTimestamp(6),
            bedsTotal: 600,
            bedsFree: 108,
            doctorsOnShift: 14,
            nursesOnShift: 38,
            oxygenCylinders: 68,
            ventilators: 28,
            medicines: { paracetamol: 445, aspirin: 292, antibiotics: 228, insulin: 172, morphine: 75 },
            incomingEmergencies: 11,
            incidentDescription: 'Construction site accident',
            aqi: 168,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(6),
        },
        {
            hospitalId: 'MED-CENTRAL-001',
            timestamp: getRandomTimestamp(7),
            bedsTotal: 600,
            bedsFree: 90,
            doctorsOnShift: 17,
            nursesOnShift: 44,
            oxygenCylinders: 85,
            ventilators: 34,
            medicines: { paracetamol: 505, aspirin: 332, antibiotics: 258, insulin: 195, morphine: 88 },
            incomingEmergencies: 8,
            incidentDescription: 'Minor traffic accident nearby',
            aqi: 152,
            festival: 'Local Festival',
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(7),
        },
        {
            hospitalId: 'MED-CENTRAL-001',
            timestamp: getRandomTimestamp(8),
            bedsTotal: 600,
            bedsFree: 102,
            doctorsOnShift: 15,
            nursesOnShift: 40,
            oxygenCylinders: 72,
            ventilators: 30,
            medicines: { paracetamol: 465, aspirin: 305, antibiotics: 238, insulin: 180, morphine: 78 },
            incomingEmergencies: 10,
            incidentDescription: 'Food poisoning outbreak at local event',
            aqi: 185,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(8),
        },
        // High Load (3 snapshots)
        {
            hospitalId: 'MED-CENTRAL-001',
            timestamp: getRandomTimestamp(9),
            bedsTotal: 600,
            bedsFree: 42,
            doctorsOnShift: 12,
            nursesOnShift: 32,
            oxygenCylinders: 48,
            ventilators: 22,
            medicines: { paracetamol: 345, aspirin: 225, antibiotics: 178, insulin: 135, morphine: 62 },
            incomingEmergencies: 18,
            incidentDescription: 'Major road accident on highway',
            aqi: 285,
            festival: 'Diwali',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(9),
        },
        {
            hospitalId: 'MED-CENTRAL-001',
            timestamp: getRandomTimestamp(10),
            bedsTotal: 600,
            bedsFree: 54,
            doctorsOnShift: 10,
            nursesOnShift: 28,
            oxygenCylinders: 55,
            ventilators: 26,
            medicines: { paracetamol: 385, aspirin: 252, antibiotics: 198, insulin: 150, morphine: 70 },
            incomingEmergencies: 22,
            incidentDescription: 'Factory fire with multiple casualties',
            aqi: 325,
            festival: 'Diwali',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(10),
        },
        {
            hospitalId: 'MED-CENTRAL-001',
            timestamp: getRandomTimestamp(11),
            bedsTotal: 600,
            bedsFree: 48,
            doctorsOnShift: 13,
            nursesOnShift: 35,
            oxygenCylinders: 62,
            ventilators: 28,
            medicines: { paracetamol: 410, aspirin: 268, antibiotics: 212, insulin: 162, morphine: 75 },
            incomingEmergencies: 20,
            incidentDescription: 'Building collapse rescue operation',
            aqi: 298,
            festival: 'New Year',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(11),
        },

        // MED-CENTRAL-002 (500 beds - Large Hospital)
        // Normal Load (4 snapshots)
        {
            hospitalId: 'MED-CENTRAL-002',
            timestamp: getRandomTimestamp(0),
            bedsTotal: 500,
            bedsFree: 125,
            doctorsOnShift: 20,
            nursesOnShift: 48,
            oxygenCylinders: 145,
            ventilators: 38,
            medicines: { paracetamol: 595, aspirin: 385, antibiotics: 298, insulin: 225, morphine: 105 },
            incomingEmergencies: 4,
            incidentDescription: 'Routine operations',
            aqi: 72,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(0),
        },
        {
            hospitalId: 'MED-CENTRAL-002',
            timestamp: getRandomTimestamp(1),
            bedsTotal: 500,
            bedsFree: 110,
            doctorsOnShift: 18,
            nursesOnShift: 44,
            oxygenCylinders: 128,
            ventilators: 34,
            medicines: { paracetamol: 535, aspirin: 348, antibiotics: 272, insulin: 205, morphine: 88 },
            incomingEmergencies: 3,
            incidentDescription: null,
            aqi: 88,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(1),
        },
        {
            hospitalId: 'MED-CENTRAL-002',
            timestamp: getRandomTimestamp(2),
            bedsTotal: 500,
            bedsFree: 138,
            doctorsOnShift: 22,
            nursesOnShift: 52,
            oxygenCylinders: 162,
            ventilators: 42,
            medicines: { paracetamol: 665, aspirin: 432, antibiotics: 338, insulin: 255, morphine: 118 },
            incomingEmergencies: 2,
            incidentDescription: 'Routine operations',
            aqi: 68,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(2),
        },
        {
            hospitalId: 'MED-CENTRAL-002',
            timestamp: getRandomTimestamp(3),
            bedsTotal: 500,
            bedsFree: 118,
            doctorsOnShift: 19,
            nursesOnShift: 46,
            oxygenCylinders: 135,
            ventilators: 36,
            medicines: { paracetamol: 565, aspirin: 368, antibiotics: 285, insulin: 215, morphine: 95 },
            incomingEmergencies: 5,
            incidentDescription: null,
            aqi: 82,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(3),
        },
        // Medium Load (5 snapshots)
        {
            hospitalId: 'MED-CENTRAL-002',
            timestamp: getRandomTimestamp(4),
            bedsTotal: 500,
            bedsFree: 72,
            doctorsOnShift: 14,
            nursesOnShift: 38,
            oxygenCylinders: 68,
            ventilators: 28,
            medicines: { paracetamol: 425, aspirin: 278, antibiotics: 218, insulin: 165, morphine: 72 },
            incomingEmergencies: 8,
            incidentDescription: 'Construction site accident',
            aqi: 138,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(4),
        },
        {
            hospitalId: 'MED-CENTRAL-002',
            timestamp: getRandomTimestamp(5),
            bedsTotal: 500,
            bedsFree: 85,
            doctorsOnShift: 16,
            nursesOnShift: 42,
            oxygenCylinders: 82,
            ventilators: 32,
            medicines: { paracetamol: 485, aspirin: 315, antibiotics: 245, insulin: 185, morphine: 82 },
            incomingEmergencies: 7,
            incidentDescription: 'Minor traffic accident nearby',
            aqi: 122,
            festival: 'Holi',
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(5),
        },
        {
            hospitalId: 'MED-CENTRAL-002',
            timestamp: getRandomTimestamp(6),
            bedsTotal: 500,
            bedsFree: 95,
            doctorsOnShift: 12,
            nursesOnShift: 34,
            oxygenCylinders: 58,
            ventilators: 24,
            medicines: { paracetamol: 385, aspirin: 252, antibiotics: 198, insulin: 150, morphine: 65 },
            incomingEmergencies: 10,
            incidentDescription: 'Food poisoning outbreak at local event',
            aqi: 172,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(6),
        },
        {
            hospitalId: 'MED-CENTRAL-002',
            timestamp: getRandomTimestamp(7),
            bedsTotal: 500,
            bedsFree: 78,
            doctorsOnShift: 15,
            nursesOnShift: 40,
            oxygenCylinders: 75,
            ventilators: 30,
            medicines: { paracetamol: 455, aspirin: 298, antibiotics: 232, insulin: 175, morphine: 78 },
            incomingEmergencies: 9,
            incidentDescription: 'Construction site accident',
            aqi: 155,
            festival: 'Local Festival',
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(7),
        },
        {
            hospitalId: 'MED-CENTRAL-002',
            timestamp: getRandomTimestamp(8),
            bedsTotal: 500,
            bedsFree: 88,
            doctorsOnShift: 13,
            nursesOnShift: 36,
            oxygenCylinders: 62,
            ventilators: 26,
            medicines: { paracetamol: 405, aspirin: 265, antibiotics: 208, insulin: 158, morphine: 68 },
            incomingEmergencies: 11,
            incidentDescription: 'Minor traffic accident nearby',
            aqi: 192,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(8),
        },
        // High Load (3 snapshots)
        {
            hospitalId: 'MED-CENTRAL-002',
            timestamp: getRandomTimestamp(9),
            bedsTotal: 500,
            bedsFree: 38,
            doctorsOnShift: 10,
            nursesOnShift: 28,
            oxygenCylinders: 42,
            ventilators: 18,
            medicines: { paracetamol: 315, aspirin: 205, antibiotics: 162, insulin: 122, morphine: 55 },
            incomingEmergencies: 19,
            incidentDescription: 'Building collapse rescue operation',
            aqi: 295,
            festival: 'Diwali',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(9),
        },
        {
            hospitalId: 'MED-CENTRAL-002',
            timestamp: getRandomTimestamp(10),
            bedsTotal: 500,
            bedsFree: 45,
            doctorsOnShift: 9,
            nursesOnShift: 26,
            oxygenCylinders: 48,
            ventilators: 22,
            medicines: { paracetamol: 355, aspirin: 232, antibiotics: 182, insulin: 138, morphine: 62 },
            incomingEmergencies: 23,
            incidentDescription: 'Major road accident on highway',
            aqi: 338,
            festival: 'New Year',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(10),
        },
        {
            hospitalId: 'MED-CENTRAL-002',
            timestamp: getRandomTimestamp(11),
            bedsTotal: 500,
            bedsFree: 42,
            doctorsOnShift: 11,
            nursesOnShift: 32,
            oxygenCylinders: 55,
            ventilators: 24,
            medicines: { paracetamol: 385, aspirin: 252, antibiotics: 198, insulin: 150, morphine: 68 },
            incomingEmergencies: 21,
            incidentDescription: 'Factory fire with multiple casualties',
            aqi: 312,
            festival: 'Diwali',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(11),
        },

        // MED-CENTRAL-003 (400 beds - Medium Hospital)
        // Normal Load (4 snapshots)
        {
            hospitalId: 'MED-CENTRAL-003',
            timestamp: getRandomTimestamp(0),
            bedsTotal: 400,
            bedsFree: 98,
            doctorsOnShift: 14,
            nursesOnShift: 32,
            oxygenCylinders: 85,
            ventilators: 28,
            medicines: { paracetamol: 485, aspirin: 315, antibiotics: 245, insulin: 185, morphine: 82 },
            incomingEmergencies: 3,
            incidentDescription: 'Routine operations',
            aqi: 75,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(0),
        },
        {
            hospitalId: 'MED-CENTRAL-003',
            timestamp: getRandomTimestamp(1),
            bedsTotal: 400,
            bedsFree: 88,
            doctorsOnShift: 12,
            nursesOnShift: 28,
            oxygenCylinders: 72,
            ventilators: 24,
            medicines: { paracetamol: 425, aspirin: 278, antibiotics: 218, insulin: 165, morphine: 72 },
            incomingEmergencies: 4,
            incidentDescription: null,
            aqi: 90,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(1),
        },
        {
            hospitalId: 'MED-CENTRAL-003',
            timestamp: getRandomTimestamp(2),
            bedsTotal: 400,
            bedsFree: 108,
            doctorsOnShift: 15,
            nursesOnShift: 36,
            oxygenCylinders: 95,
            ventilators: 32,
            medicines: { paracetamol: 545, aspirin: 355, antibiotics: 278, insulin: 210, morphine: 92 },
            incomingEmergencies: 2,
            incidentDescription: 'Routine operations',
            aqi: 65,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(2),
        },
        {
            hospitalId: 'MED-CENTRAL-003',
            timestamp: getRandomTimestamp(3),
            bedsTotal: 400,
            bedsFree: 92,
            doctorsOnShift: 13,
            nursesOnShift: 30,
            oxygenCylinders: 78,
            ventilators: 26,
            medicines: { paracetamol: 455, aspirin: 298, antibiotics: 232, insulin: 175, morphine: 78 },
            incomingEmergencies: 5,
            incidentDescription: null,
            aqi: 85,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(3),
        },
        // Medium Load (5 snapshots)
        {
            hospitalId: 'MED-CENTRAL-003',
            timestamp: getRandomTimestamp(4),
            bedsTotal: 400,
            bedsFree: 58,
            doctorsOnShift: 10,
            nursesOnShift: 26,
            oxygenCylinders: 48,
            ventilators: 20,
            medicines: { paracetamol: 345, aspirin: 225, antibiotics: 178, insulin: 135, morphine: 58 },
            incomingEmergencies: 8,
            incidentDescription: 'Food poisoning outbreak at local event',
            aqi: 142,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(4),
        },
        {
            hospitalId: 'MED-CENTRAL-003',
            timestamp: getRandomTimestamp(5),
            bedsTotal: 400,
            bedsFree: 68,
            doctorsOnShift: 11,
            nursesOnShift: 30,
            oxygenCylinders: 58,
            ventilators: 24,
            medicines: { paracetamol: 395, aspirin: 258, antibiotics: 202, insulin: 152, morphine: 68 },
            incomingEmergencies: 7,
            incidentDescription: 'Construction site accident',
            aqi: 125,
            festival: 'Holi',
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(5),
        },
        {
            hospitalId: 'MED-CENTRAL-003',
            timestamp: getRandomTimestamp(6),
            bedsTotal: 400,
            bedsFree: 75,
            doctorsOnShift: 9,
            nursesOnShift: 24,
            oxygenCylinders: 42,
            ventilators: 18,
            medicines: { paracetamol: 315, aspirin: 205, antibiotics: 162, insulin: 122, morphine: 52 },
            incomingEmergencies: 10,
            incidentDescription: 'Minor traffic accident nearby',
            aqi: 178,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(6),
        },
        {
            hospitalId: 'MED-CENTRAL-003',
            timestamp: getRandomTimestamp(7),
            bedsTotal: 400,
            bedsFree: 62,
            doctorsOnShift: 12,
            nursesOnShift: 28,
            oxygenCylinders: 52,
            ventilators: 22,
            medicines: { paracetamol: 365, aspirin: 238, antibiotics: 188, insulin: 142, morphine: 62 },
            incomingEmergencies: 9,
            incidentDescription: 'Food poisoning outbreak at local event',
            aqi: 158,
            festival: 'Local Festival',
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(7),
        },
        {
            hospitalId: 'MED-CENTRAL-003',
            timestamp: getRandomTimestamp(8),
            bedsTotal: 400,
            bedsFree: 72,
            doctorsOnShift: 10,
            nursesOnShift: 25,
            oxygenCylinders: 45,
            ventilators: 19,
            medicines: { paracetamol: 335, aspirin: 218, antibiotics: 172, insulin: 130, morphine: 55 },
            incomingEmergencies: 11,
            incidentDescription: 'Construction site accident',
            aqi: 195,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(8),
        },
        // High Load (3 snapshots)
        {
            hospitalId: 'MED-CENTRAL-003',
            timestamp: getRandomTimestamp(9),
            bedsTotal: 400,
            bedsFree: 32,
            doctorsOnShift: 7,
            nursesOnShift: 20,
            oxygenCylinders: 32,
            ventilators: 14,
            medicines: { paracetamol: 265, aspirin: 172, antibiotics: 138, insulin: 105, morphine: 45 },
            incomingEmergencies: 17,
            incidentDescription: 'Major road accident on highway',
            aqi: 305,
            festival: 'Diwali',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(9),
        },
        {
            hospitalId: 'MED-CENTRAL-003',
            timestamp: getRandomTimestamp(10),
            bedsTotal: 400,
            bedsFree: 38,
            doctorsOnShift: 6,
            nursesOnShift: 18,
            oxygenCylinders: 38,
            ventilators: 16,
            medicines: { paracetamol: 295, aspirin: 192, antibiotics: 152, insulin: 115, morphine: 50 },
            incomingEmergencies: 21,
            incidentDescription: 'Factory fire with multiple casualties',
            aqi: 348,
            festival: 'New Year',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(10),
        },
        {
            hospitalId: 'MED-CENTRAL-003',
            timestamp: getRandomTimestamp(11),
            bedsTotal: 400,
            bedsFree: 35,
            doctorsOnShift: 8,
            nursesOnShift: 24,
            oxygenCylinders: 42,
            ventilators: 18,
            medicines: { paracetamol: 315, aspirin: 205, antibiotics: 162, insulin: 122, morphine: 55 },
            incomingEmergencies: 19,
            incidentDescription: 'Building collapse rescue operation',
            aqi: 322,
            festival: 'Diwali',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(11),
        },

        // MED-CENTRAL-004 (300 beds - Medium Hospital)
        // Normal Load (4 snapshots)
        {
            hospitalId: 'MED-CENTRAL-004',
            timestamp: getRandomTimestamp(0),
            bedsTotal: 300,
            bedsFree: 72,
            doctorsOnShift: 12,
            nursesOnShift: 28,
            oxygenCylinders: 65,
            ventilators: 22,
            medicines: { paracetamol: 405, aspirin: 265, antibiotics: 208, insulin: 158, morphine: 68 },
            incomingEmergencies: 3,
            incidentDescription: 'Routine operations',
            aqi: 78,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(0),
        },
        {
            hospitalId: 'MED-CENTRAL-004',
            timestamp: getRandomTimestamp(1),
            bedsTotal: 300,
            bedsFree: 65,
            doctorsOnShift: 11,
            nursesOnShift: 25,
            oxygenCylinders: 58,
            ventilators: 20,
            medicines: { paracetamol: 365, aspirin: 238, antibiotics: 188, insulin: 142, morphine: 62 },
            incomingEmergencies: 4,
            incidentDescription: null,
            aqi: 92,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(1),
        },
        {
            hospitalId: 'MED-CENTRAL-004',
            timestamp: getRandomTimestamp(2),
            bedsTotal: 300,
            bedsFree: 82,
            doctorsOnShift: 14,
            nursesOnShift: 32,
            oxygenCylinders: 78,
            ventilators: 26,
            medicines: { paracetamol: 455, aspirin: 298, antibiotics: 232, insulin: 175, morphine: 78 },
            incomingEmergencies: 2,
            incidentDescription: 'Routine operations',
            aqi: 68,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(2),
        },
        {
            hospitalId: 'MED-CENTRAL-004',
            timestamp: getRandomTimestamp(3),
            bedsTotal: 300,
            bedsFree: 68,
            doctorsOnShift: 13,
            nursesOnShift: 30,
            oxygenCylinders: 62,
            ventilators: 21,
            medicines: { paracetamol: 385, aspirin: 252, antibiotics: 198, insulin: 150, morphine: 65 },
            incomingEmergencies: 5,
            incidentDescription: null,
            aqi: 85,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(3),
        },
        // Medium Load (5 snapshots)
        {
            hospitalId: 'MED-CENTRAL-004',
            timestamp: getRandomTimestamp(4),
            bedsTotal: 300,
            bedsFree: 45,
            doctorsOnShift: 9,
            nursesOnShift: 24,
            oxygenCylinders: 38,
            ventilators: 16,
            medicines: { paracetamol: 295, aspirin: 192, antibiotics: 152, insulin: 115, morphine: 50 },
            incomingEmergencies: 8,
            incidentDescription: 'Minor traffic accident nearby',
            aqi: 145,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(4),
        },
        {
            hospitalId: 'MED-CENTRAL-004',
            timestamp: getRandomTimestamp(5),
            bedsTotal: 300,
            bedsFree: 52,
            doctorsOnShift: 10,
            nursesOnShift: 27,
            oxygenCylinders: 45,
            ventilators: 19,
            medicines: { paracetamol: 335, aspirin: 218, antibiotics: 172, insulin: 130, morphine: 58 },
            incomingEmergencies: 7,
            incidentDescription: 'Food poisoning outbreak at local event',
            aqi: 128,
            festival: 'Holi',
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(5),
        },
        {
            hospitalId: 'MED-CENTRAL-004',
            timestamp: getRandomTimestamp(6),
            bedsTotal: 300,
            bedsFree: 58,
            doctorsOnShift: 8,
            nursesOnShift: 22,
            oxygenCylinders: 35,
            ventilators: 15,
            medicines: { paracetamol: 265, aspirin: 172, antibiotics: 138, insulin: 105, morphine: 45 },
            incomingEmergencies: 10,
            incidentDescription: 'Construction site accident',
            aqi: 182,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(6),
        },
        {
            hospitalId: 'MED-CENTRAL-004',
            timestamp: getRandomTimestamp(7),
            bedsTotal: 300,
            bedsFree: 48,
            doctorsOnShift: 11,
            nursesOnShift: 26,
            oxygenCylinders: 42,
            ventilators: 18,
            medicines: { paracetamol: 315, aspirin: 205, antibiotics: 162, insulin: 122, morphine: 55 },
            incomingEmergencies: 9,
            incidentDescription: 'Minor traffic accident nearby',
            aqi: 162,
            festival: 'Local Festival',
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(7),
        },
        {
            hospitalId: 'MED-CENTRAL-004',
            timestamp: getRandomTimestamp(8),
            bedsTotal: 300,
            bedsFree: 55,
            doctorsOnShift: 9,
            nursesOnShift: 23,
            oxygenCylinders: 38,
            ventilators: 16,
            medicines: { paracetamol: 285, aspirin: 185, antibiotics: 145, insulin: 110, morphine: 48 },
            incomingEmergencies: 11,
            incidentDescription: 'Food poisoning outbreak at local event',
            aqi: 198,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(8),
        },
        // High Load (3 snapshots)
        {
            hospitalId: 'MED-CENTRAL-004',
            timestamp: getRandomTimestamp(9),
            bedsTotal: 300,
            bedsFree: 25,
            doctorsOnShift: 6,
            nursesOnShift: 18,
            oxygenCylinders: 28,
            ventilators: 12,
            medicines: { paracetamol: 225, aspirin: 148, antibiotics: 118, insulin: 90, morphine: 38 },
            incomingEmergencies: 18,
            incidentDescription: 'Building collapse rescue operation',
            aqi: 315,
            festival: 'Diwali',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(9),
        },
        {
            hospitalId: 'MED-CENTRAL-004',
            timestamp: getRandomTimestamp(10),
            bedsTotal: 300,
            bedsFree: 30,
            doctorsOnShift: 5,
            nursesOnShift: 16,
            oxygenCylinders: 32,
            ventilators: 13,
            medicines: { paracetamol: 245, aspirin: 162, antibiotics: 128, insulin: 98, morphine: 42 },
            incomingEmergencies: 22,
            incidentDescription: 'Major road accident on highway',
            aqi: 358,
            festival: 'New Year',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(10),
        },
        {
            hospitalId: 'MED-CENTRAL-004',
            timestamp: getRandomTimestamp(11),
            bedsTotal: 300,
            bedsFree: 28,
            doctorsOnShift: 7,
            nursesOnShift: 20,
            oxygenCylinders: 35,
            ventilators: 15,
            medicines: { paracetamol: 265, aspirin: 172, antibiotics: 138, insulin: 105, morphine: 45 },
            incomingEmergencies: 20,
            incidentDescription: 'Factory fire with multiple casualties',
            aqi: 332,
            festival: 'Diwali',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(11),
        },

        // MED-CENTRAL-005 (200 beds - Small Hospital)
        // Normal Load (4 snapshots)
        {
            hospitalId: 'MED-CENTRAL-005',
            timestamp: getRandomTimestamp(0),
            bedsTotal: 200,
            bedsFree: 48,
            doctorsOnShift: 8,
            nursesOnShift: 20,
            oxygenCylinders: 42,
            ventilators: 16,
            medicines: { paracetamol: 315, aspirin: 205, antibiotics: 162, insulin: 122, morphine: 55 },
            incomingEmergencies: 3,
            incidentDescription: 'Routine operations',
            aqi: 75,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(0),
        },
        {
            hospitalId: 'MED-CENTRAL-005',
            timestamp: getRandomTimestamp(1),
            bedsTotal: 200,
            bedsFree: 42,
            doctorsOnShift: 7,
            nursesOnShift: 18,
            oxygenCylinders: 38,
            ventilators: 14,
            medicines: { paracetamol: 285, aspirin: 185, antibiotics: 145, insulin: 110, morphine: 48 },
            incomingEmergencies: 4,
            incidentDescription: null,
            aqi: 90,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(1),
        },
        {
            hospitalId: 'MED-CENTRAL-005',
            timestamp: getRandomTimestamp(2),
            bedsTotal: 200,
            bedsFree: 55,
            doctorsOnShift: 9,
            nursesOnShift: 23,
            oxygenCylinders: 48,
            ventilators: 18,
            medicines: { paracetamol: 355, aspirin: 232, antibiotics: 182, insulin: 138, morphine: 62 },
            incomingEmergencies: 2,
            incidentDescription: 'Routine operations',
            aqi: 68,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(2),
        },
        {
            hospitalId: 'MED-CENTRAL-005',
            timestamp: getRandomTimestamp(3),
            bedsTotal: 200,
            bedsFree: 45,
            doctorsOnShift: 8,
            nursesOnShift: 21,
            oxygenCylinders: 40,
            ventilators: 15,
            medicines: { paracetamol: 305, aspirin: 198, antibiotics: 155, insulin: 118, morphine: 52 },
            incomingEmergencies: 5,
            incidentDescription: null,
            aqi: 85,
            festival: null,
            newsSummary: 'Normal patient flow',
            createdAt: getRandomTimestamp(3),
        },
        // Medium Load (5 snapshots)
        {
            hospitalId: 'MED-CENTRAL-005',
            timestamp: getRandomTimestamp(4),
            bedsTotal: 200,
            bedsFree: 28,
            doctorsOnShift: 6,
            nursesOnShift: 16,
            oxygenCylinders: 28,
            ventilators: 11,
            medicines: { paracetamol: 225, aspirin: 148, antibiotics: 118, insulin: 90, morphine: 38 },
            incomingEmergencies: 8,
            incidentDescription: 'Construction site accident',
            aqi: 148,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(4),
        },
        {
            hospitalId: 'MED-CENTRAL-005',
            timestamp: getRandomTimestamp(5),
            bedsTotal: 200,
            bedsFree: 35,
            doctorsOnShift: 7,
            nursesOnShift: 19,
            oxygenCylinders: 32,
            ventilators: 13,
            medicines: { paracetamol: 255, aspirin: 165, antibiotics: 132, insulin: 100, morphine: 45 },
            incomingEmergencies: 7,
            incidentDescription: 'Minor traffic accident nearby',
            aqi: 132,
            festival: 'Holi',
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(5),
        },
        {
            hospitalId: 'MED-CENTRAL-005',
            timestamp: getRandomTimestamp(6),
            bedsTotal: 200,
            bedsFree: 38,
            doctorsOnShift: 5,
            nursesOnShift: 15,
            oxygenCylinders: 25,
            ventilators: 10,
            medicines: { paracetamol: 205, aspirin: 135, antibiotics: 108, insulin: 82, morphine: 35 },
            incomingEmergencies: 10,
            incidentDescription: 'Food poisoning outbreak at local event',
            aqi: 188,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(6),
        },
        {
            hospitalId: 'MED-CENTRAL-005',
            timestamp: getRandomTimestamp(7),
            bedsTotal: 200,
            bedsFree: 32,
            doctorsOnShift: 7,
            nursesOnShift: 18,
            oxygenCylinders: 30,
            ventilators: 12,
            medicines: { paracetamol: 235, aspirin: 152, antibiotics: 122, insulin: 92, morphine: 40 },
            incomingEmergencies: 9,
            incidentDescription: 'Construction site accident',
            aqi: 165,
            festival: 'Local Festival',
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(7),
        },
        {
            hospitalId: 'MED-CENTRAL-005',
            timestamp: getRandomTimestamp(8),
            bedsTotal: 200,
            bedsFree: 36,
            doctorsOnShift: 6,
            nursesOnShift: 16,
            oxygenCylinders: 27,
            ventilators: 11,
            medicines: { paracetamol: 215, aspirin: 142, antibiotics: 112, insulin: 85, morphine: 37 },
            incomingEmergencies: 11,
            incidentDescription: 'Minor traffic accident nearby',
            aqi: 202,
            festival: null,
            newsSummary: 'Increased patient admissions',
            createdAt: getRandomTimestamp(8),
        },
        // High Load (3 snapshots)
        {
            hospitalId: 'MED-CENTRAL-005',
            timestamp: getRandomTimestamp(9),
            bedsTotal: 200,
            bedsFree: 18,
            doctorsOnShift: 4,
            nursesOnShift: 12,
            oxygenCylinders: 20,
            ventilators: 8,
            medicines: { paracetamol: 175, aspirin: 115, antibiotics: 92, insulin: 70, morphine: 30 },
            incomingEmergencies: 16,
            incidentDescription: 'Major road accident on highway',
            aqi: 325,
            festival: 'Diwali',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(9),
        },
        {
            hospitalId: 'MED-CENTRAL-005',
            timestamp: getRandomTimestamp(10),
            bedsTotal: 200,
            bedsFree: 20,
            doctorsOnShift: 4,
            nursesOnShift: 11,
            oxygenCylinders: 22,
            ventilators: 9,
            medicines: { paracetamol: 185, aspirin: 122, antibiotics: 98, insulin: 75, morphine: 32 },
            incomingEmergencies: 20,
            incidentDescription: 'Factory fire with multiple casualties',
            aqi: 365,
            festival: 'New Year',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(10),
        },
        {
            hospitalId: 'MED-CENTRAL-005',
            timestamp: getRandomTimestamp(11),
            bedsTotal: 200,
            bedsFree: 19,
            doctorsOnShift: 5,
            nursesOnShift: 14,
            oxygenCylinders: 25,
            ventilators: 10,
            medicines: { paracetamol: 195, aspirin: 128, antibiotics: 102, insulin: 78, morphine: 35 },
            incomingEmergencies: 18,
            incidentDescription: 'Building collapse rescue operation',
            aqi: 342,
            festival: 'Diwali',
            newsSummary: 'Emergency protocol activated due to mass casualty incident',
            createdAt: getRandomTimestamp(11),
        },
    ];

    await db.insert(hospitalSnapshots).values(sampleSnapshots);
    
    console.log('✅ Snapshots seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});